### ISSUE TITLE
Request: Add support for Pepco (Maryland) Green Button Data

### ISSUE THREAD

**Issue by dan-nunes** [gauthig/greenbutton-influxdb#26]
Thanks for your efforts on this project! Attempting to set it up with my local utility provider, Pepco, the format of their residential net metering data is notably different than the SCE example provided. I've attached an example in case you might be able to add support in a future release.
[example_pep_electric_interval_data_Service 1_2021-12-06_to_2022-12-06.csv](https://github.com/gauthig/greenbutton-influxdb/files/10175986/example_pep_electric_interval_data_Service.1_2021-12-06_to_2022-12-06.csv)

**Comment by gauthig** [comment]
I'll take a look at this

**Comment by gauthig** [comment]
Added Pepco and cost field since Pepco provides it.
Current sample grafana dashboard need to be fixed due to new fields and changes in field names.  Coming soon.  But you can build your own dashboards or modify the existing by changing measurement and fields.

Will create new dashboard with variables and selections to assist with changes better.

**Comment by gauthig** [comment]
Closed - In release 1.5
